/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as KontaktRouteImport } from './routes/kontakt'
import { Route as PriserRouteImport } from './routes/priser'
import { Route as TjansterRouteImport } from './routes/tjanster'
import { Route as VanligaFragorRouteImport } from './routes/vanliga-fragor'
import { Route as AuthenticatedAdminRouteRouteImport } from './routes/_authenticated/admin/route'
import { Route as AuthenticatedPortalRouteRouteImport } from './routes/_authenticated/portal/route'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin/index'
import { Route as AuthenticatedAdminIncidenterRouteImport } from './routes/_authenticated/admin/incidenter'
import { Route as AuthenticatedAdminIntegrationerRouteImport } from './routes/_authenticated/admin/integrationer'
import { Route as AuthenticatedAdminKunderRouteImport } from './routes/_authenticated/admin/kunder'
import { Route as AuthenticatedAdminOnboardingRouteImport } from './routes/_authenticated/admin/onboarding'
import { Route as AuthenticatedAdminPlanerRouteImport } from './routes/_authenticated/admin/planer'
import { Route as AuthenticatedAdminRapporterRouteImport } from './routes/_authenticated/admin/rapporter'
import { Route as AuthenticatedAdminSupportRouteImport } from './routes/_authenticated/admin/support'
import { Route as AuthenticatedPortalIndexRouteImport } from './routes/_authenticated/portal/index'
import { Route as AuthenticatedPortalRapporterRouteImport } from './routes/_authenticated/portal/rapporter'
import { Route as AuthenticatedPortalSupportRouteImport } from './routes/_authenticated/portal/support'
import { Route as AuthenticatedRapportReportIdRouteImport } from './routes/_authenticated/rapport.$reportId'
import { Route as AuthenticatedAdminSajterIndexRouteImport } from './routes/_authenticated/admin/sajter/index'
import { Route as AuthenticatedAdminSajterSiteIdRouteImport } from './routes/_authenticated/admin/sajter/$siteId'
import { Route as AuthenticatedPortalSajterSiteIdRouteImport } from './routes/_authenticated/portal/sajter.$siteId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const KontaktRoute = KontaktRouteImport.update({
  id: '/kontakt',
  path: '/kontakt',
  getParentRoute: () => rootRouteImport,
} as any)
const PriserRoute = PriserRouteImport.update({
  id: '/priser',
  path: '/priser',
  getParentRoute: () => rootRouteImport,
} as any)
const TjansterRoute = TjansterRouteImport.update({
  id: '/tjanster',
  path: '/tjanster',
  getParentRoute: () => rootRouteImport,
} as any)
const VanligaFragorRoute = VanligaFragorRouteImport.update({
  id: '/vanliga-fragor',
  path: '/vanliga-fragor',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRouteRoute = AuthenticatedAdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPortalRouteRoute =
  AuthenticatedPortalRouteRouteImport.update({
    id: '/portal',
    path: '/portal',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRouteRoute,
} as any)
const AuthenticatedAdminIncidenterRoute =
  AuthenticatedAdminIncidenterRouteImport.update({
    id: '/incidenter',
    path: '/incidenter',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminIntegrationerRoute =
  AuthenticatedAdminIntegrationerRouteImport.update({
    id: '/integrationer',
    path: '/integrationer',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminKunderRoute =
  AuthenticatedAdminKunderRouteImport.update({
    id: '/kunder',
    path: '/kunder',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminOnboardingRoute =
  AuthenticatedAdminOnboardingRouteImport.update({
    id: '/onboarding',
    path: '/onboarding',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminPlanerRoute =
  AuthenticatedAdminPlanerRouteImport.update({
    id: '/planer',
    path: '/planer',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminRapporterRoute =
  AuthenticatedAdminRapporterRouteImport.update({
    id: '/rapporter',
    path: '/rapporter',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminSupportRoute =
  AuthenticatedAdminSupportRouteImport.update({
    id: '/support',
    path: '/support',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedPortalIndexRoute =
  AuthenticatedPortalIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedPortalRouteRoute,
  } as any)
const AuthenticatedPortalRapporterRoute =
  AuthenticatedPortalRapporterRouteImport.update({
    id: '/rapporter',
    path: '/rapporter',
    getParentRoute: () => AuthenticatedPortalRouteRoute,
  } as any)
const AuthenticatedPortalSupportRoute =
  AuthenticatedPortalSupportRouteImport.update({
    id: '/support',
    path: '/support',
    getParentRoute: () => AuthenticatedPortalRouteRoute,
  } as any)
const AuthenticatedRapportReportIdRoute =
  AuthenticatedRapportReportIdRouteImport.update({
    id: '/rapport/$reportId',
    path: '/rapport/$reportId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminSajterIndexRoute =
  AuthenticatedAdminSajterIndexRouteImport.update({
    id: '/sajter/',
    path: '/sajter/',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminSajterSiteIdRoute =
  AuthenticatedAdminSajterSiteIdRouteImport.update({
    id: '/sajter/$siteId',
    path: '/sajter/$siteId',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedPortalSajterSiteIdRoute =
  AuthenticatedPortalSajterSiteIdRouteImport.update({
    id: '/sajter/$siteId',
    path: '/sajter/$siteId',
    getParentRoute: () => AuthenticatedPortalRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/kontakt': typeof KontaktRoute
  '/priser': typeof PriserRoute
  '/tjanster': typeof TjansterRoute
  '/vanliga-fragor': typeof VanligaFragorRoute
  '/admin': typeof AuthenticatedAdminRouteRouteWithChildren
  '/portal': typeof AuthenticatedPortalRouteRouteWithChildren
  '/admin/incidenter': typeof AuthenticatedAdminIncidenterRoute
  '/admin/integrationer': typeof AuthenticatedAdminIntegrationerRoute
  '/admin/kunder': typeof AuthenticatedAdminKunderRoute
  '/admin/onboarding': typeof AuthenticatedAdminOnboardingRoute
  '/admin/planer': typeof AuthenticatedAdminPlanerRoute
  '/admin/rapporter': typeof AuthenticatedAdminRapporterRoute
  '/admin/support': typeof AuthenticatedAdminSupportRoute
  '/portal/rapporter': typeof AuthenticatedPortalRapporterRoute
  '/portal/support': typeof AuthenticatedPortalSupportRoute
  '/rapport/$reportId': typeof AuthenticatedRapportReportIdRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/portal/': typeof AuthenticatedPortalIndexRoute
  '/admin/sajter/$siteId': typeof AuthenticatedAdminSajterSiteIdRoute
  '/portal/sajter/$siteId': typeof AuthenticatedPortalSajterSiteIdRoute
  '/admin/sajter/': typeof AuthenticatedAdminSajterIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/kontakt': typeof KontaktRoute
  '/priser': typeof PriserRoute
  '/tjanster': typeof TjansterRoute
  '/vanliga-fragor': typeof VanligaFragorRoute
  '/admin/incidenter': typeof AuthenticatedAdminIncidenterRoute
  '/admin/integrationer': typeof AuthenticatedAdminIntegrationerRoute
  '/admin/kunder': typeof AuthenticatedAdminKunderRoute
  '/admin/onboarding': typeof AuthenticatedAdminOnboardingRoute
  '/admin/planer': typeof AuthenticatedAdminPlanerRoute
  '/admin/rapporter': typeof AuthenticatedAdminRapporterRoute
  '/admin/support': typeof AuthenticatedAdminSupportRoute
  '/portal/rapporter': typeof AuthenticatedPortalRapporterRoute
  '/portal/support': typeof AuthenticatedPortalSupportRoute
  '/rapport/$reportId': typeof AuthenticatedRapportReportIdRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/portal': typeof AuthenticatedPortalIndexRoute
  '/admin/sajter/$siteId': typeof AuthenticatedAdminSajterSiteIdRoute
  '/portal/sajter/$siteId': typeof AuthenticatedPortalSajterSiteIdRoute
  '/admin/sajter': typeof AuthenticatedAdminSajterIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/kontakt': typeof KontaktRoute
  '/priser': typeof PriserRoute
  '/tjanster': typeof TjansterRoute
  '/vanliga-fragor': typeof VanligaFragorRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteRouteWithChildren
  '/_authenticated/portal': typeof AuthenticatedPortalRouteRouteWithChildren
  '/_authenticated/admin/incidenter': typeof AuthenticatedAdminIncidenterRoute
  '/_authenticated/admin/integrationer': typeof AuthenticatedAdminIntegrationerRoute
  '/_authenticated/admin/kunder': typeof AuthenticatedAdminKunderRoute
  '/_authenticated/admin/onboarding': typeof AuthenticatedAdminOnboardingRoute
  '/_authenticated/admin/planer': typeof AuthenticatedAdminPlanerRoute
  '/_authenticated/admin/rapporter': typeof AuthenticatedAdminRapporterRoute
  '/_authenticated/admin/support': typeof AuthenticatedAdminSupportRoute
  '/_authenticated/portal/rapporter': typeof AuthenticatedPortalRapporterRoute
  '/_authenticated/portal/support': typeof AuthenticatedPortalSupportRoute
  '/_authenticated/rapport/$reportId': typeof AuthenticatedRapportReportIdRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/portal/': typeof AuthenticatedPortalIndexRoute
  '/_authenticated/admin/sajter/$siteId': typeof AuthenticatedAdminSajterSiteIdRoute
  '/_authenticated/portal/sajter/$siteId': typeof AuthenticatedPortalSajterSiteIdRoute
  '/_authenticated/admin/sajter/': typeof AuthenticatedAdminSajterIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/kontakt'
    | '/priser'
    | '/tjanster'
    | '/vanliga-fragor'
    | '/admin'
    | '/portal'
    | '/admin/incidenter'
    | '/admin/integrationer'
    | '/admin/kunder'
    | '/admin/onboarding'
    | '/admin/planer'
    | '/admin/rapporter'
    | '/admin/support'
    | '/portal/rapporter'
    | '/portal/support'
    | '/rapport/$reportId'
    | '/admin/'
    | '/portal/'
    | '/admin/sajter/$siteId'
    | '/portal/sajter/$siteId'
    | '/admin/sajter/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/kontakt'
    | '/priser'
    | '/tjanster'
    | '/vanliga-fragor'
    | '/admin/incidenter'
    | '/admin/integrationer'
    | '/admin/kunder'
    | '/admin/onboarding'
    | '/admin/planer'
    | '/admin/rapporter'
    | '/admin/support'
    | '/portal/rapporter'
    | '/portal/support'
    | '/rapport/$reportId'
    | '/admin'
    | '/portal'
    | '/admin/sajter/$siteId'
    | '/portal/sajter/$siteId'
    | '/admin/sajter'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/kontakt'
    | '/priser'
    | '/tjanster'
    | '/vanliga-fragor'
    | '/_authenticated/admin'
    | '/_authenticated/portal'
    | '/_authenticated/admin/incidenter'
    | '/_authenticated/admin/integrationer'
    | '/_authenticated/admin/kunder'
    | '/_authenticated/admin/onboarding'
    | '/_authenticated/admin/planer'
    | '/_authenticated/admin/rapporter'
    | '/_authenticated/admin/support'
    | '/_authenticated/portal/rapporter'
    | '/_authenticated/portal/support'
    | '/_authenticated/rapport/$reportId'
    | '/_authenticated/admin/'
    | '/_authenticated/portal/'
    | '/_authenticated/admin/sajter/$siteId'
    | '/_authenticated/portal/sajter/$siteId'
    | '/_authenticated/admin/sajter/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  KontaktRoute: typeof KontaktRoute
  PriserRoute: typeof PriserRoute
  TjansterRoute: typeof TjansterRoute
  VanligaFragorRoute: typeof VanligaFragorRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kontakt': {
      id: '/kontakt'
      path: '/kontakt'
      fullPath: '/kontakt'
      preLoaderRoute: typeof KontaktRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/priser': {
      id: '/priser'
      path: '/priser'
      fullPath: '/priser'
      preLoaderRoute: typeof PriserRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tjanster': {
      id: '/tjanster'
      path: '/tjanster'
      fullPath: '/tjanster'
      preLoaderRoute: typeof TjansterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vanliga-fragor': {
      id: '/vanliga-fragor'
      path: '/vanliga-fragor'
      fullPath: '/vanliga-fragor'
      preLoaderRoute: typeof VanligaFragorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/portal': {
      id: '/_authenticated/portal'
      path: '/portal'
      fullPath: '/portal'
      preLoaderRoute: typeof AuthenticatedPortalRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/incidenter': {
      id: '/_authenticated/admin/incidenter'
      path: '/incidenter'
      fullPath: '/admin/incidenter'
      preLoaderRoute: typeof AuthenticatedAdminIncidenterRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/integrationer': {
      id: '/_authenticated/admin/integrationer'
      path: '/integrationer'
      fullPath: '/admin/integrationer'
      preLoaderRoute: typeof AuthenticatedAdminIntegrationerRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/kunder': {
      id: '/_authenticated/admin/kunder'
      path: '/kunder'
      fullPath: '/admin/kunder'
      preLoaderRoute: typeof AuthenticatedAdminKunderRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/onboarding': {
      id: '/_authenticated/admin/onboarding'
      path: '/onboarding'
      fullPath: '/admin/onboarding'
      preLoaderRoute: typeof AuthenticatedAdminOnboardingRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/planer': {
      id: '/_authenticated/admin/planer'
      path: '/planer'
      fullPath: '/admin/planer'
      preLoaderRoute: typeof AuthenticatedAdminPlanerRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/rapporter': {
      id: '/_authenticated/admin/rapporter'
      path: '/rapporter'
      fullPath: '/admin/rapporter'
      preLoaderRoute: typeof AuthenticatedAdminRapporterRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/support': {
      id: '/_authenticated/admin/support'
      path: '/support'
      fullPath: '/admin/support'
      preLoaderRoute: typeof AuthenticatedAdminSupportRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/portal/': {
      id: '/_authenticated/portal/'
      path: '/'
      fullPath: '/portal/'
      preLoaderRoute: typeof AuthenticatedPortalIndexRouteImport
      parentRoute: typeof AuthenticatedPortalRouteRoute
    }
    '/_authenticated/portal/rapporter': {
      id: '/_authenticated/portal/rapporter'
      path: '/rapporter'
      fullPath: '/portal/rapporter'
      preLoaderRoute: typeof AuthenticatedPortalRapporterRouteImport
      parentRoute: typeof AuthenticatedPortalRouteRoute
    }
    '/_authenticated/portal/support': {
      id: '/_authenticated/portal/support'
      path: '/support'
      fullPath: '/portal/support'
      preLoaderRoute: typeof AuthenticatedPortalSupportRouteImport
      parentRoute: typeof AuthenticatedPortalRouteRoute
    }
    '/_authenticated/rapport/$reportId': {
      id: '/_authenticated/rapport/$reportId'
      path: '/rapport/$reportId'
      fullPath: '/rapport/$reportId'
      preLoaderRoute: typeof AuthenticatedRapportReportIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/sajter/': {
      id: '/_authenticated/admin/sajter/'
      path: '/sajter'
      fullPath: '/admin/sajter/'
      preLoaderRoute: typeof AuthenticatedAdminSajterIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/sajter/$siteId': {
      id: '/_authenticated/admin/sajter/$siteId'
      path: '/sajter/$siteId'
      fullPath: '/admin/sajter/$siteId'
      preLoaderRoute: typeof AuthenticatedAdminSajterSiteIdRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/portal/sajter/$siteId': {
      id: '/_authenticated/portal/sajter/$siteId'
      path: '/sajter/$siteId'
      fullPath: '/portal/sajter/$siteId'
      preLoaderRoute: typeof AuthenticatedPortalSajterSiteIdRouteImport
      parentRoute: typeof AuthenticatedPortalRouteRoute
    }
  }
}

interface AuthenticatedAdminRouteRouteChildren {
  AuthenticatedAdminIncidenterRoute: typeof AuthenticatedAdminIncidenterRoute
  AuthenticatedAdminIntegrationerRoute: typeof AuthenticatedAdminIntegrationerRoute
  AuthenticatedAdminKunderRoute: typeof AuthenticatedAdminKunderRoute
  AuthenticatedAdminOnboardingRoute: typeof AuthenticatedAdminOnboardingRoute
  AuthenticatedAdminPlanerRoute: typeof AuthenticatedAdminPlanerRoute
  AuthenticatedAdminRapporterRoute: typeof AuthenticatedAdminRapporterRoute
  AuthenticatedAdminSupportRoute: typeof AuthenticatedAdminSupportRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
  AuthenticatedAdminSajterSiteIdRoute: typeof AuthenticatedAdminSajterSiteIdRoute
  AuthenticatedAdminSajterIndexRoute: typeof AuthenticatedAdminSajterIndexRoute
}

const AuthenticatedAdminRouteRouteChildren: AuthenticatedAdminRouteRouteChildren =
  {
    AuthenticatedAdminIncidenterRoute: AuthenticatedAdminIncidenterRoute,
    AuthenticatedAdminIntegrationerRoute: AuthenticatedAdminIntegrationerRoute,
    AuthenticatedAdminKunderRoute: AuthenticatedAdminKunderRoute,
    AuthenticatedAdminOnboardingRoute: AuthenticatedAdminOnboardingRoute,
    AuthenticatedAdminPlanerRoute: AuthenticatedAdminPlanerRoute,
    AuthenticatedAdminRapporterRoute: AuthenticatedAdminRapporterRoute,
    AuthenticatedAdminSupportRoute: AuthenticatedAdminSupportRoute,
    AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
    AuthenticatedAdminSajterSiteIdRoute: AuthenticatedAdminSajterSiteIdRoute,
    AuthenticatedAdminSajterIndexRoute: AuthenticatedAdminSajterIndexRoute,
  }

const AuthenticatedAdminRouteRouteWithChildren =
  AuthenticatedAdminRouteRoute._addFileChildren(
    AuthenticatedAdminRouteRouteChildren,
  )

interface AuthenticatedPortalRouteRouteChildren {
  AuthenticatedPortalRapporterRoute: typeof AuthenticatedPortalRapporterRoute
  AuthenticatedPortalSupportRoute: typeof AuthenticatedPortalSupportRoute
  AuthenticatedPortalIndexRoute: typeof AuthenticatedPortalIndexRoute
  AuthenticatedPortalSajterSiteIdRoute: typeof AuthenticatedPortalSajterSiteIdRoute
}

const AuthenticatedPortalRouteRouteChildren: AuthenticatedPortalRouteRouteChildren =
  {
    AuthenticatedPortalRapporterRoute: AuthenticatedPortalRapporterRoute,
    AuthenticatedPortalSupportRoute: AuthenticatedPortalSupportRoute,
    AuthenticatedPortalIndexRoute: AuthenticatedPortalIndexRoute,
    AuthenticatedPortalSajterSiteIdRoute: AuthenticatedPortalSajterSiteIdRoute,
  }

const AuthenticatedPortalRouteRouteWithChildren =
  AuthenticatedPortalRouteRoute._addFileChildren(
    AuthenticatedPortalRouteRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRouteRoute: typeof AuthenticatedAdminRouteRouteWithChildren
  AuthenticatedPortalRouteRoute: typeof AuthenticatedPortalRouteRouteWithChildren
  AuthenticatedRapportReportIdRoute: typeof AuthenticatedRapportReportIdRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRouteRoute: AuthenticatedAdminRouteRouteWithChildren,
  AuthenticatedPortalRouteRoute: AuthenticatedPortalRouteRouteWithChildren,
  AuthenticatedRapportReportIdRoute: AuthenticatedRapportReportIdRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  KontaktRoute: KontaktRoute,
  PriserRoute: PriserRoute,
  TjansterRoute: TjansterRoute,
  VanligaFragorRoute: VanligaFragorRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
