/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as KontaktRouteImport } from './routes/kontakt'
import { Route as PriserRouteImport } from './routes/priser'
import { Route as TjansterRouteImport } from './routes/tjanster'
import { Route as VanligaFragorRouteImport } from './routes/vanliga-fragor'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const KontaktRoute = KontaktRouteImport.update({
  id: '/kontakt',
  path: '/kontakt',
  getParentRoute: () => rootRouteImport,
} as any)
const PriserRoute = PriserRouteImport.update({
  id: '/priser',
  path: '/priser',
  getParentRoute: () => rootRouteImport,
} as any)
const TjansterRoute = TjansterRouteImport.update({
  id: '/tjanster',
  path: '/tjanster',
  getParentRoute: () => rootRouteImport,
} as any)
const VanligaFragorRoute = VanligaFragorRouteImport.update({
  id: '/vanliga-fragor',
  path: '/vanliga-fragor',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/kontakt': typeof KontaktRoute
  '/priser': typeof PriserRoute
  '/tjanster': typeof TjansterRoute
  '/vanliga-fragor': typeof VanligaFragorRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/kontakt': typeof KontaktRoute
  '/priser': typeof PriserRoute
  '/tjanster': typeof TjansterRoute
  '/vanliga-fragor': typeof VanligaFragorRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/kontakt': typeof KontaktRoute
  '/priser': typeof PriserRoute
  '/tjanster': typeof TjansterRoute
  '/vanliga-fragor': typeof VanligaFragorRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    '/' | '/auth' | '/kontakt' | '/priser' | '/tjanster' | '/vanliga-fragor'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/auth' | '/kontakt' | '/priser' | '/tjanster' | '/vanliga-fragor'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/kontakt'
    | '/priser'
    | '/tjanster'
    | '/vanliga-fragor'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  KontaktRoute: typeof KontaktRoute
  PriserRoute: typeof PriserRoute
  TjansterRoute: typeof TjansterRoute
  VanligaFragorRoute: typeof VanligaFragorRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kontakt': {
      id: '/kontakt'
      path: '/kontakt'
      fullPath: '/kontakt'
      preLoaderRoute: typeof KontaktRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/priser': {
      id: '/priser'
      path: '/priser'
      fullPath: '/priser'
      preLoaderRoute: typeof PriserRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tjanster': {
      id: '/tjanster'
      path: '/tjanster'
      fullPath: '/tjanster'
      preLoaderRoute: typeof TjansterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vanliga-fragor': {
      id: '/vanliga-fragor'
      path: '/vanliga-fragor'
      fullPath: '/vanliga-fragor'
      preLoaderRoute: typeof VanligaFragorRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  KontaktRoute: KontaktRoute,
  PriserRoute: PriserRoute,
  TjansterRoute: TjansterRoute,
  VanligaFragorRoute: VanligaFragorRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
