/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PriserRouteImport } from './routes/priser'
import { Route as TjansterRouteImport } from './routes/tjanster'
import { Route as VanligaFragorRouteImport } from './routes/vanliga-fragor'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PriserRoute = PriserRouteImport.update({
  id: '/priser',
  path: '/priser',
  getParentRoute: () => rootRouteImport,
} as any)
const TjansterRoute = TjansterRouteImport.update({
  id: '/tjanster',
  path: '/tjanster',
  getParentRoute: () => rootRouteImport,
} as any)
const VanligaFragorRoute = VanligaFragorRouteImport.update({
  id: '/vanliga-fragor',
  path: '/vanliga-fragor',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/priser': typeof PriserRoute
  '/tjanster': typeof TjansterRoute
  '/vanliga-fragor': typeof VanligaFragorRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/priser': typeof PriserRoute
  '/tjanster': typeof TjansterRoute
  '/vanliga-fragor': typeof VanligaFragorRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/priser': typeof PriserRoute
  '/tjanster': typeof TjansterRoute
  '/vanliga-fragor': typeof VanligaFragorRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/priser' | '/tjanster' | '/vanliga-fragor'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/priser' | '/tjanster' | '/vanliga-fragor'
  id: '__root__' | '/' | '/priser' | '/tjanster' | '/vanliga-fragor'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PriserRoute: typeof PriserRoute
  TjansterRoute: typeof TjansterRoute
  VanligaFragorRoute: typeof VanligaFragorRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/priser': {
      id: '/priser'
      path: '/priser'
      fullPath: '/priser'
      preLoaderRoute: typeof PriserRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tjanster': {
      id: '/tjanster'
      path: '/tjanster'
      fullPath: '/tjanster'
      preLoaderRoute: typeof TjansterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vanliga-fragor': {
      id: '/vanliga-fragor'
      path: '/vanliga-fragor'
      fullPath: '/vanliga-fragor'
      preLoaderRoute: typeof VanligaFragorRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PriserRoute: PriserRoute,
  TjansterRoute: TjansterRoute,
  VanligaFragorRoute: VanligaFragorRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
